---
- name: Build docker image from java artifact
  hosts: localhost 
  tasks:
    - name: confirm that python package manager is installed
      ansible.builtin.apt:
        name: pip
        state: latest 
        update_cache: true
    - name: confirming docker module for python
      ansible.builtin.pip:
        name: docker 
        state: latest
      become: True
    - name: Login to dockerhub
      community.docker.docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
    - name: 
      debug:
        var: 
          - build_number
          - workspace
    # - name: Build docker image
    #   community.docker.docker_image:
    #     name: "java_hello_world:{{ build_number }}"
    #     build:
    #       path: "{{ workspace }}"
    #     source: build
    #     state: present
        