---
- name: Build docker image from java artifact
  hosts: localhost 
  tasks:
    - name: confirm that python package manager is installed
      ansible.builtin.apt:
        name: pip
        state: latest 
        update_cache: true
    - name: confirming docker module for python
      ansible.builtin.pip:
        name: docker 
        state: latest
      become: True
    - name: Login to dockerhub
      community.docker.docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
    - name: Build docker image
      community.docker.docker_image:
        name: "java-hello-world:v{{ build_number }}"
        build:
          path: "{{ workspace }}"
        source: build
        state: present
        push: true
        repository: kerracan/java-hello-world
        tag: latest
        force_tag: true
        